version: '3.1'

services:
  front-end:
    build:
      context: ./apps/zoom-clone-fe
    ports:
      - "3000:3000"
    entrypoint: npm
    command: ["run", "start", "-workspace", "@zoom-clone/fe"]
    volumes:
      - ./:/var/app
    depends_on:
      - back-end

  back-end:
    build:
      context: ./apps/zoom-clone-be
    ports:
      - "8080:8080"
    entrypoint: npm
    command: ["run", "start", "-workspace", "@zoom-clone/be"]
    volumes:
      - ./:/var/app
